baseURL = "https://jonathanj.in"
languageCode = "en-us"
title = "Jonathan Jin"
theme = "avicenna"
# googleAnalytics = "UA-1234-6"
timeout=3000

[params]
  subtitle= "Machine Learning Software Engineer"
  interests="Machine Learning"
  cv_name= "resume.pdf"
  # blog="http://myblog.edu"

# [[params.affilation]]
#   name = "Stanford University"
#   position = "PhD Student"
#   contact = "hadi@cs.stanford.edu"

[[params.affilation]]
  name = "NVIDIA"
  position = "Senior Systems Software Engineer, AI Infrastructure"
  contact = "jonathanj@nvidia.com"

[[params.social]]
  name = "GitHub"
  icon = "github"
  url = "https://github.com/jinnovation"

[[params.social]]
  name = "Twitter"
  icon = "twitter"
  url = "https://twitter.com/NotJinterested"


[[params.social]]
  name = "LinkedIn"
  icon = "linkedin"
  url = "https://linkedin.com/in/jinnovation"


[[params.introduction.paragraph]]
  text="""
  I am a NYC-based software engineer, currently working on AI infrastructure for
  autonomous vehicle development at NVIDIA. Previous, I was a member of
  <a href="http://cortex.twitter.com">Twitter Cortex</a> and the Machine Learning
  Platform Tools team.
  """

[[params.introduction.paragraph]]
  text="""
  I'm interested in building large-scale, high-performance production machine
  learning systems for compelling use cases -- particularly those with stringent
  requirements around scalability, traceability, and verifiability. More
  broadly, I'm particularly interested in opportunities to explore the
  intersection of machine learning theory and engineering.
  """

[[params.projects]]
  [[params.projects.project]]
    name = "derain-net"
    project_page = "https://github.com/jinnovation/derain-net"
    code_link = "https://github.com/jinnovation/derain-net"
    description = "A (WIP) TensorFlow reproduction of Fu, Huang, Ding, Liao, and Paisley’s method for single-image rain removal (https://arxiv.org/abs/1609.02087)"

# 		name = "Velit egestas dui id ornare arcu odio ut sem. Nec nam aliquam sem et tortor"
# 		description  = "Enim facilisis gravida neque convallis a. Suspendisse potenti nullam ac tortor vitae purus faucibus ornare suspendisse.Velit egestas dui id ornare arcu odio ut sem. Nec nam aliquam sem et tortor. In nisl nisi scelerisque eu ultrices vitae auctor."
# 		project_page = "https://myprojecthomepage.com"
# 		code_link = "https://coderepo.com"
# 		blog_link = "https://ablogpost.com"

#  [[params.projects.project]]
# 		name = "In nisl nisi scelerisque eu ultrices vitae auctor"
# 		description  = ""
# 		project_page = "https://myprojecthomepage.com"
# 		code_link = "https://coderepo.com"
# 		blog_link = ""

#  [[params.projects.project]]
# 		name = "Integer eget aliquet nibh praesent tristique magna"
# 		description  = ""
# 		project_page = "https://myprojecthomepage.com"
# 		code_link = ""
# 		blog_link = "https://ablogpost.com"

[[params.publications]]
  year="2018"

  [[params.publications.paper]]
    name = "Engineering a Job-based Forecasting Workflow for Observability Anomaly Detection"
    # authors = "__Jonathan Jin__"
    dest  = "Uber Engineering Blog"
    link = "http://eng.uber.com/observability-anomaly-detection/"
    # code_link = "https://thecoderepo.com"
    # blog_link = "https://myblogaboutit.com"

  [[params.publications.paper]]
    name = "Implementing Model-Agnosticism in Uber's Real-Time Anomaly Detection Platform"
    # authors = "__Hadi Sinaee__,Les Larkins, Edra Ethier"
    dest  = "Uber Engineering Blog"
    link = "https://mypaperishere.com"
    # code_link = "https://thecoderepo.com"
    # blog_link = "https://myblogaboutit.com"

