#+TITLE: Home
#+AUTHOR: Jonathan Jin
#+URI: /
#+EMAIL: jjin082693@gmail.com

#+OPTIONS: num:nil todo:nil

I am a NYC-based software engineer. I'm currently at [[https://www.uber.com][Uber]] as a member of
Observability Applications.

** DONE Professional Interests

   I'm interested in *research engineering* and *machine learning infrastructure
   engineering* positions.

   More broadly, I'm especially interested in opportunities that operate at the
   intersection of *research* and *engineering*. To that end, the roles that
   most excite me provide opportunities to explore my interests in AI/ML; how
   they might be implemented or productized both scalably and performantly; and
   bring those research and modelling findings into production.

   If you and your team are working on projects that I'd make a good addition
   for, let's talk.

** Research Interests

   My research interests lie in the fields of *machine learning*, *knowledge
   representation*, and *decision theory*.

   Specifically, I am drawn to the following questions:

   - What is *knowledge*? What does it mean to *know* something? Can a machine
     that achieves near-human performance at some task be said to truly *know*
     and *understand* that task beyond a behavioristic interpretation thereof?

   - How do we *model* and *represent* that knowledge to achieve precision,
     recall, and performance on par with -- possibly even beyond -- humans?

   - Traditional machines reason with "explicit" logic -- conditionals,
     pattern-matching, etc. How can we, as engineers, design and implement
     systems that can reason about *ambiguity* and *uncertainty*?
   
** Contact

   - GitHub :: [[https://github.com/jinnovation][github.com/jinnovation]]
   - LinkedIn :: [[https://linkedin.com/in/jinnovation][linkedin.com/in/jinnovation]]
   - Email :: <first initial><last name>082693<at>gmail.com
